# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: infrastructure
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Npm@1 
    # Install dependencies
  - script: npm install
    displayName: "Install linting, test and coverage dependencies"

    # Execute unit tests
  - script: npm run test-ci
    displayName: "Execute unit tests"
       