parameters:
  - name: environment
    type: string
  - name: dependsOn
    type: object
    default: ['deploy_to_test']
  - name: condition
    type: string
    default: 'succeeded()'
stages:
  - stage: deploy_to_${{parameters.environment}}
    displayName: Deploy to ${{parameters.environment}}
    dependsOn:
      - Build
      - ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs:
      - job: PulumiDeploy
        pool:
          vmImage: ubuntu-latest
        steps:
        - script: pulumi stack select ${{parameters.environment}}
          workingDirectory: $(System.DefaultWorkingDirectory)
          env:
           PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
        - script: npm run pulumi-preview:${{parameters.environment}}
          workingDirectory: $(System.DefaultWorkingDirectory)
          env:
            PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
