parameters:
  - name: environment
    type: string
  - name: userName
    type: string
  - name: password
    type: string
  - name: dependsOn
    type: object
    default: ['deploy_to_test']
  - name: condition
    type: string
    default: 'succeeded()'
stages:
  - stage: deploy_to_${{parameters.environment}}
    displayName: Deploy to ${{parameters.environment}}
    dependsOn:
      - Build
      - ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs:
      - deployment: Deploy
        variables:
          chrono.tag: $[stageDependencies.Build.Build.outputs['GetPackageVersion.chrono.tag']]
        displayName: Deploy to ${{parameters.environment}}
        pool:
          vmImage: ubuntu-latest
        environment:
          name: ${{parameters.environment}}
      - job: PulumiDeploy
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Npm@1 
           # Install dependencies
        - script: npm install
          workingDirectory: $(System.DefaultWorkingDirectory)
          displayName: "Install linting, test and coverage dependencies"

           # Azure login
        - script: az login -u ${{parameters.userName}} -p ${{parameters.password}}
          workingDirectory: $(System.DefaultWorkingDirectory)

           # Deploy Pulumi 
        - script: pulumi stack select ${{parameters.environment}}
          workingDirectory: $(System.DefaultWorkingDirectory)
          env:
           PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
        - script: npm run pulumi-preview:${{parameters.environment}}
          workingDirectory: $(System.DefaultWorkingDirectory)
          env:
            PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
